export const appData = [
    {
        "label": "Accessibility",
        "index": 13,
        "list": [
            "No compliance",
            "25% ADA Compliant",
            "50% ADA Compliant",
            "75% ADA Compliant",
            "100% ADA Compliant",
            "25% WCAG Compliant",
            "50% WCAG Compliant",
            "75% WCAG Compliant",
            "100% WCAG Compliant"
        ]
    },
    {
        "label": "Benefits",
        "index": 3,
        "list": [
            "401K Matching",
            "Company equity: stock options",
            "Continuing Education stipend",
            "Commute reimbursement",
            "Flexible work schedule",
            "Paid Vacations",
            "Paid Sick Days",
            "Paid Holidays",
            "Paid Personal Days",
            "Paid Maternity Leave (Female)",
            "Paid Maternity Leave (Male)",
            "Free Breakfast",
            "Free Lunch",
            "Free Dinner",
            "Some meals provided",
            "Free Soda",
            "Free Snacks",
            "Free Gym",
            "Team workouts",
            "Game room",
            "Free Swag",
            "Personal Parking Space",
            "Private Office",
            "Discounts",
            "Insurance: Medical",
            "Insurance: Dental",
            "Insurance: Vision"
        ]
    },
    {
        "label": "Commute",
        "index": 4,
        "list": [
            "5 miles max",
            "10 miles max",
            "15 miles max",
            "20 miles max",
            "25 miles max",
            "50 miles max",
            "75 miles max",
            "100 miles max",
            "5 minutes max",
            "10 minutes max",
            "15 minutes max",
            "20 minutes max",
            "30 minutes max",
            "60 minutes max",
            "120 minutes max"
        ]
    },
    {
        "label": "Popular Company",
        "index": 5,
        "list": [
            "ADP",
            "Adobe",
            "Airbnb",
            "Amazon",
            "Apple",
            "Bank of America",
            "Box Internet",
            "CDW",
            "Capital One",
            "Cisco",
            "Citi",
            "Coinbase",
            "Comcast",
            "Dell",
            "Deloitte",
            "Discover",
            "DocuSign",
            "Dropbox",
            "EY",
            "Facebook",
            "GE",
            "Github",
            "Goldman Sachs",
            "Google",
            "Intel",
            "JPMorgan Chase & Co.",
            "Johnson & Johnson",
            "LinkedIn",
            "Lyft",
            "McKinsey & Company",
            "Microsoft",
            "NVIDIA",
            "Netflix",
            "Nike",
            "Oracle",
            "PayPal",
            "Pinterest",
            "PwC",
            "REI",
            "Rubric",
            "SAP Computer Software",
            "Salesforce",
            "ServiceNow",
            "Slack",
            "Snowflake",
            "SpaceX",
            "Splunk",
            "Spotify",
            "Tesla",
            "The We Company",
            "Twitter",
            "Uber",
            "Verizon",
            "Walt Disney Company",
            "Wells Fargo",
            "Workday"
        ]
    },
    {
        "label": "Company Size",
        "index": 6,
        "list": [
            "1-10",
            "11-50",
            "51-100",
            "101-200",
            "201-500",
            "500-1k",
            "1k-5k",
            "5k-10k",
            "10k-50k",
            "500k-100k",
            "More than 100k"
        ]
    },
    {
        "label": "Dress Code",
        "index": 14,
        "list": [
            "No dress code",
            "Shorts or Jeans and T-shirts",
            "Jeans and T-shirts",
            "Business Casual",
            "Suits Required",
            "Suit and Tie Required"
        ]
    },
    {
        "label": "Education Required",
        "index": 7,
        "list": [
            "High School Equivalency",
            "High School Diploma",
            "Boot-Camp (less than 1 year)",
            "Tech-School (1+ years)",
            "Associates Degree (2 years)",
            "Bachelor of Science (4 years)",
            "Masters Degree (5-6 years)",
            "Phd",
            "Post-Doc"
        ]
    },
    {
        "label": "Employee Type",
        "index": 8,
        "list": [
            "Full-Time",
            "Part-Time",
            "Contract Independent",
            "Contract W2",
            "Contract to Hire Independent",
            "Contract to Hire W2",
            "Third Party",
            "Internship",
            "Temporary"
        ]
    },
    {
        "label": "Experience Level",
        "index": 9,
        "list": [
            "Intern",
            "Junior",
            "Senior"
        ]
    },
    {
        "label": "Industry",
        "index": 2,
        "list": [
            "Accounting",
            "Adult",
            "Aerospace",
            "Agriculture",
            "Arts",
            "Banking",
            "Bars",
            "Business Services",
            "Construction",
            "Defense",
            "Education",
            "Entertainment",
            "Finance",
            "Food Services",
            "Forestry",
            "Government",
            "Healthcare",
            "Information Technology",
            "Insurance",
            "Legal",
            "Maintenance",
            "Manufacturing",
            "Medical",
            "Museum",
            "Recreation",
            "Repair",
            "Restaurants",
            "Retail",
            "Transportation"
        ]
    },
    {
        "label": "Internal External",
        "index": 10,
        "list": [
            "Interal Employee facing only",
            "External Customer facing only",
            "Mostly Internal Some External",
            "Some Internal Mostly External",
            "Half Internal Half External"
        ]
    },
    {
        "label": "Methodology",
        "index": 11,
        "list": [
            "Waterfall",
            "Agile",
            "Scrum",
            "Kanban",
            "Lean",
            "Six Sigma",
            "PMI/PMBok"
        ]
    },
    {
        "label": "Mobile",
        "index": 12,
        "list": [
            "Web Only",
            "Mobile Only",
            "Responsive Design",
            "Mobile Only and Web Only",
            "Mobile Only and Responsive Design"
        ]
    },
    {
        "label": "Payment",
        "index": 1,
        "list": [
            "$20+ per hour",
            "$30+ per hour",
            "$40+ per hour",
            "$50+ per hour",
            "$60+ per hour",
            "$70+ per hour",
            "$80+ per hour",
            "$90+ per hour",
            "$100+ per hour",
            "$125+ per hour",
            "$150+ per hour",
            "$175+ per hour",
            "$200+ per hour",
            "$250+ per hour",
            "$500+ per week",
            "$750+ per week",
            "$1k+ per week",
            "$2k+ per week",
            "$3k+ per week",
            "$4k+ per week",
            "$5k+ per week",
            "$6k+ per week",
            "$7k+ per week",
            "$8k+ per week",
            "$9k+ per week",
            "$10k+ per week",
            "$20k+ per week",
            "$30k+ per week",
            "$40k+ per week",
            "$2k+ per month",
            "$3k+ per month",
            "$4k+ per month",
            "$5k+ per month",
            "$6k+ per month",
            "$7k+ per month",
            "$8k+ per month",
            "$9k+ per month",
            "$10k+ per month",
            "$20k+ per month",
            "$30k+ per month",
            "$40k+ per month",
            "$50k+ per year",
            "$60k+ per year",
            "$70k+ per year",
            "$80k+ per year",
            "$90k+ per year",
            "$100k+ per year",
            "$125k+ per year",
            "$150k+ per year",
            "$175k+ per year",
            "$200k+ per year",
            "$250k+ per year",
            "$275k+ per year",
            "$300k+ per year",
            "$400k+ per year",
            "$500k+ per year"
        ]
    },
    {
        "label": "Pets Allowed",
        "index": 15,
        "list": [
            "No pets allowed",
            "Dogs allowed",
            "Cats allowed",
            "Cats and Dogs allowed",
            "All pets allowed"
        ]
    },
    {
        "label": "Tech Stack",
        "index": 0,
        "list": [
            "Angular JS 1.x",
            "Angular 2.x",
            "Angular 4.x",
            "Angular 5.x",
            "Angular 6.x",
            "Angular 7.x",
            "Angular 8.x",
            "Angular 9.x",
            "Backbone 1.x",
            "Bootstrap 1.x",
            "Bootstrap 2.x",
            "Bootstrap 3.x",
            "Bootstrap 4.x",
            "Bootstrap 5.x",
            "CSS1",
            "CSS2",
            "CSS3",
            "CSS4",
            "Handlebars 1.x",
            "Handlebars 2.x",
            "Handlebars 3.x",
            "Handlebars 4.x",
            "Handlebars 5.x Beta",
            "HTML 3.x",
            "HTML 4.x",
            "HTML5",
            "JavaScript ES5 ECMAScript 5 2009",
            "JavaScript ES6 ECMAScript 2015",
            "JavaScript ES7 ECMAScript 2016",
            "JavaScript ES8 ECMAScript 2017",
            "JavaScript ES9 ECMAScript 2018",
            "JavaScript ES10 ECMAScript 2019",
            "JavaScript ES11 ECMAScript 2020",
            "JavaScript ES12 ECMAScript 2021",
            "Jenkins 1.x",
            "Jenkins 2.x",
            "jQuery 1.x",
            "jQuery 2.x",
            "jQuery 3.x",
            "Less.js 1.x",
            "Less.js 2.x",
            "Less.js 3.x",
            "Less.js 4.x",
            "React 15.x",
            "React 16.x",
            "React 17.x",
            "Redux 1.x",
            "Redux 2.x",
            "Redux 3.x",
            "Redux 4.x",
            "SASS 1.x",
            "SASS 2.x",
            "SASS 3.x",
            "SASS 4.x",
            "SASS 5.x",
            "TypeScript 1.x",
            "TypeScript 2.x",
            "TypeScript 3.x",
            "TypeScript 4.x",
            "Vue 0.x",
            "Vue 1.x",
            "Vue 2.x",
            "Vue 3.x",
            "Vuex 1.x",
            "Vuex 2.x",
            "Vuex 3.x"
        ]
    },
    {
        "label": "Working From Home",
        "index": 16,
        "list": [
            "0% Never",
            "10%",
            "20%",
            "25%",
            "30%",
            "40%",
            "50%",
            "75%",
            "80%",
            "90%",
            "100% Always"
        ]
    }
];